
from textaugH.Word2vec_augmentation import Word2VecAugmentation
from textaugH.Bert_context_augmentation import BertContextAugmentation
from textaugH.Translate_aug import Translate
from textaugH.Random_swap import RandomSwapAug
from textaugH.Word_deletion import WordDeletion
from textaugH.Preprocessing import TextPreprocessor